from django.urls import path
from .views import (
    create_comment,
    create_group,
    create_post,
    delete_post,
    get_post,
    get_posts_reacted_by_user,
    get_reaction_metrics,
    get_reactions_to_post,
    get_replies_for_comment,
    get_total_reactions,
    get_user_posts,
    react_to_comment,
    react_to_post,
    remove_member_from_group,
    reply_to_comment,
    add_member_to_group,
    get_posts_with_more_positive_reactions,
    get_group_feed,
    get_posts_with_more_comments_than_reactions,
    get_silent_group_members,
    make_member_as_admin,
)

urlpatterns = [
    path("create-post/", create_post),
    path("create-comment/", create_comment),
    path("reply-to-comment/", reply_to_comment),
    path("react-to-post/", react_to_post),
    path("react-to-comment/", react_to_comment),
    path("get-total-reactions/", get_total_reactions),
    path("get_reaction_metrics/", get_reaction_metrics),
    path("get-reaction-metrics/<str:post_id>/", get_reaction_metrics),
    path("delete/<str:post_id>/", delete_post),
    path("get-posts-with-more-positive-reactions/", get_posts_with_more_positive_reactions),
    path("get-posts-reacted-by-user/", get_posts_reacted_by_user),
    path("get-reactions-to-post/", get_reactions_to_post),
    path("get-post/", get_post),
    path("get-user-posts/", get_user_posts),
    path("get-replies-for-comment/", get_replies_for_comment),
    path("create-group/", create_group),
    path("add-member-to-group/", add_member_to_group),
    path("remove-member-from-group/", remove_member_from_group),
    path("make-member-as-admin/", make_member_as_admin),
    path("get-group-feed/", get_group_feed),
    path("get-posts-with-more-comments-than-reactions/", get_posts_with_more_comments_than_reactions),
    path("get-silent-group-members/", get_silent_group_members),
]
